"use client"

import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import { Badge } from "@/components/ui/badge"
import type { PricingV2Model } from "@/types/pricing"

const show = (value: unknown) => value === null || value === undefined || value === "" ? "—" : String(value)
const yesNo = (value: boolean | null | undefined) => value ? "Yes" : "No"
const money = (value: number | null | undefined, currency: string) => value === null || value === undefined ? "—" : `${currency} ${value.toFixed(2)}`
function Facts({ items }: { items: Array<[string, unknown]> }) { return <dl className="grid gap-x-4 gap-y-2 md:grid-cols-3">{items.map(([label, value]) => <div key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd>{show(value)}</dd></div>)}</dl> }
function State({ enabled }: { enabled: boolean | null | undefined }) { return <Badge variant={enabled ? "default" : "secondary"}>{enabled ? "Enabled" : "Disabled"}</Badge> }

export function PricingModelDetails({ item }: { item: PricingV2Model }) {
  return <Accordion type="multiple" className="rounded-md border px-3">
    <AccordionItem value="scope"><AccordionTrigger>Scope, lifecycle, and audit</AccordionTrigger><AccordionContent><Facts items={[["Pricing ID", item.id], ["Scope", item.pricingType], ["Owner ID", item.ownerId], ["Zone code", item.zoneCode], ["Zone display name", item.zoneDisplayName], ["Currency", item.currency], ["Effective from", item.effectiveFrom], ["Effective to", item.effectiveTo], ["Created by", item.audit?.createdBy], ["Created at", item.audit?.createdAt], ["Updated by", item.audit?.updatedBy], ["Updated at", item.audit?.updatedAt]]} /></AccordionContent></AccordionItem>
    <AccordionItem value="weight"><AccordionTrigger>Dimensional and chargeable weight</AccordionTrigger><AccordionContent className="space-y-3"><div className="flex gap-2"><State enabled={item.dimensionalWeight.enabled} /><span className="font-medium">{item.dimensionalWeight.displayName || "Dimensional weight"}</span></div><Facts items={[["Unit", item.dimensionalWeight.unit], ["Divisor", item.dimensionalWeight.divisor], ["Rounding scale", item.dimensionalWeight.roundingScale], ["Rounding mode", item.dimensionalWeight.roundingMode], ["Chargeable weight enabled", yesNo(item.chargeableWeight.enabled)], ["Chargeable display name", item.chargeableWeight.displayName], ["Chargeable calculation", item.chargeableWeight.calculationType]]} /></AccordionContent></AccordionItem>
    <AccordionItem value="packages"><AccordionTrigger>Package pricing slabs ({item.packageSlabs?.length || 0})</AccordionTrigger><AccordionContent className="space-y-3">{item.packageSlabs?.map((slab, index) => <div key={`${slab.slabCode}-${index}`} className="rounded-md border p-3"><div className="mb-2 flex flex-wrap items-center gap-2"><State enabled={slab.enabled} /><span className="font-medium">{slab.displayName || slab.slabCode}</span><Badge variant="outline">Tier {slab.tierOrder}</Badge></div><Facts items={[["Code", slab.slabCode], ["Base price", money(slab.basePrice, item.currency)], ["Weight range kg", `${show(slab.minChargeableWeightKgExclusive)} < weight ≤ ${show(slab.maxChargeableWeightKg)}`], ["Dimension sum range cm", `${show(slab.minDimensionSumCmExclusive)} < sum ≤ ${show(slab.maxDimensionSumCm)}`]]} /></div>)}</AccordionContent></AccordionItem>
    <AccordionItem value="distance"><AccordionTrigger>Distance pricing ({item.distancePricing?.distanceSlabs?.length || 0} slabs)</AccordionTrigger><AccordionContent className="space-y-3"><div className="flex gap-2"><State enabled={item.distancePricing.enabled} /><span className="font-medium">{item.distancePricing.displayName || "Distance pricing"}</span></div><Facts items={[["Included distance", `${show(item.distancePricing.includedDistanceKm)} km`]]} />{item.distancePricing.distanceSlabs?.map((slab, index) => <div key={`${slab.slabCode}-${index}`} className="rounded-md border p-3"><div className="mb-2 flex gap-2"><State enabled={slab.enabled} /><span className="font-medium">{slab.displayName || slab.slabCode}</span></div><Facts items={[["Code", slab.slabCode], ["Range", `${show(slab.fromKmExclusive)} < km ≤ ${show(slab.toKmInclusive)}`], ["Calculation", slab.calculationType], ["Rate", money(slab.rate, item.currency)]]} /></div>)}</AccordionContent></AccordionItem>
    <AccordionItem value="surcharges"><AccordionTrigger>Surcharges ({item.surcharges?.length || 0})</AccordionTrigger><AccordionContent className="space-y-3">{item.surcharges?.length ? item.surcharges.map((rule, index) => <div key={`${rule.surchargeCode}-${index}`} className="rounded-md border p-3"><div className="mb-2 flex gap-2"><State enabled={rule.enabled} /><span className="font-medium">{rule.displayName || rule.surchargeCode}</span></div><Facts items={[["Code", rule.surchargeCode], ["Description", rule.description], ["Trigger", rule.triggerType], ["Trigger value", rule.triggerValue], ["Time window", rule.startTime || rule.endTime ? `${show(rule.startTime)} – ${show(rule.endTime)}` : "—"], ["Timezone", rule.timezone], ["Calculation", rule.calculationType], ["Amount", money(rule.amount, item.currency)], ["Percentage", rule.percentage === null ? "—" : `${show(rule.percentage)}%`], ["Percentage base", rule.percentageBase]]} /></div>) : <p className="text-muted-foreground">No surcharges configured.</p>}</AccordionContent></AccordionItem>
    <AccordionItem value="taxes"><AccordionTrigger>Taxes ({item.taxes?.length || 0})</AccordionTrigger><AccordionContent className="space-y-3">{item.taxes?.length ? item.taxes.map((tax, index) => <div key={`${tax.taxCode}-${index}`} className="rounded-md border p-3"><div className="mb-2 flex gap-2"><State enabled={tax.enabled} /><span className="font-medium">{tax.displayName || tax.taxCode}</span></div><Facts items={[["Code", tax.taxCode], ["Calculation", tax.calculationType], ["Percentage", `${tax.percentage}%`], ["Percentage base", tax.percentageBase]]} /></div>) : <p className="text-muted-foreground">No taxes configured.</p>}</AccordionContent></AccordionItem>
    <AccordionItem value="advanced"><AccordionTrigger>Custom quotes and rounding</AccordionTrigger><AccordionContent className="space-y-3"><div className="flex gap-2"><State enabled={item.customQuoteRules?.enabled} /><span className="font-medium">Distance-based custom quote rule</span></div><Facts items={[["Max standard distance", item.customQuoteRules?.maxStandardDistanceKm === null ? "—" : `${show(item.customQuoteRules?.maxStandardDistanceKm)} km`], ["Distance exceeded message", item.customQuoteRules?.distanceExceededMessage], ["Money scale", item.rounding?.moneyScale], ["Money rounding", item.rounding?.moneyRoundingMode], ["Measurement scale", item.rounding?.measurementScale], ["Measurement rounding", item.rounding?.measurementRoundingMode]]} /></AccordionContent></AccordionItem>
  </Accordion>
}
